package com.dazhuangzhou.dao;

import com.dazhuangzhou.vo.model.NewsVO;
import com.dazhuangzhou.vo.model.NewsVOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int countByExample(NewsVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int deleteByExample(NewsVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int insert(NewsVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int insertSelective(NewsVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    List<NewsVO> selectByExample(NewsVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    NewsVO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") NewsVO record, @Param("example") NewsVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int updateByExample(@Param("record") NewsVO record, @Param("example") NewsVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int updateByPrimaryKeySelective(NewsVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated Sat Jul 02 14:54:59 CST 2016
     */
    int updateByPrimaryKey(NewsVO record);
}